vich_uploader:
    db_driver: orm

    mappings:
        lodgingPictures:
            uri_prefix: /assets/img/lodging
            upload_destination: '%kernel.project_dir%/public/assets/img/lodging'

        userPictures:
            uri_prefix: /assets/img/user
            upload_destination: '%kernel.project_dir%/public/assets/img/user'
